name: myspace_core
description: "MySpace Core"
version: 0.0.1
homepage: www.shoh.dev

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Shared
  myspace_design_system: ^0.0.1
  myspace_ui: ^0.0.1

  # Etc
  intl: ^0.19.0
  go_router: ^14.8.1

  # Data
  get_it: ^8.0.3
  freezed_annotation: ^3.0.0
  dio: ^5.8.0+1
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.4

flutter: