name: myspace_core
description: "MySpace Core"
version: 0.0.1
homepage: www.shoh.dev
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Shared
  myspace_ui:
    path: ../myspace_ui

  # Etc
  intl: ^0.19.0

  # Data
  # get_it: ^8.0.3
  freezed_annotation: ^2.4.4
  dio: ^5.8.0+1
  provider: ^6.1.4
  bot_toast: ^4.1.3
  logging: ^1.3.0
  go_router: ^15.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.4.4

flutter: