name: myspace_core
description: "MySpace Core"
version: 0.0.1
homepage: www.shoh.dev
publish_to: 'none'

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Shared
  myspace_ui:
    path: ../myspace_ui

  # Etc
  intl: ^0.20.0

  # Data
  dio: ^5.8.0+1
  provider: ^6.1.4
  bot_toast: ^4.1.3
  logging: ^1.3.0
  go_router: ^16.0.0
  mutex: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: